module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_MAX_HP: 100,
  PLAYER_TURN_SPEED: Math.PI / 48,
  PLAYER_FIRE_COOLDOWN: 0.25,
  PLAYER_MIN_SPEED: 200,
  PLAYER_SPEED: 400,
  PLAYER_MAX_SPEED: 800,
  PLAYER_ACCELERATION: 5,

  BIRD_RADIUS: 30,
  BIRD_SPEED: 800,
  BIRD_RADIANS_WIDTH: Math.PI / 8,

  BIRD_TOTAL: 1000,

  SCORE_BULLET_HIT: 20,
  SCORE_PER_SECOND: 1,

  VIEW_DISTANCE: 800,

  MAP_SIZE: 3000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead',
  },
});
